// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14.02.2025, 04:53:12
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/vuuud/Desktop/Bilski/TheraApp/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vuuud/Desktop/Bilski/TheraApp/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vuuud/Desktop/Bilski/TheraApp/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vuuud/Desktop/Bilski/TheraApp/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vuuud/Desktop/Bilski/TheraApp/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vuuud/Desktop/Bilski/TheraApp/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/vuuud/Desktop/Bilski/TheraApp/frontend/composables/**/*.{js,ts,mjs}","C:/Users/vuuud/Desktop/Bilski/TheraApp/frontend/utils/**/*.{js,ts,mjs}","C:/Users/vuuud/Desktop/Bilski/TheraApp/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vuuud/Desktop/Bilski/TheraApp/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vuuud/Desktop/Bilski/TheraApp/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;